# Generated by Django 4.2.5 on 2023-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_alter_category_options_alter_sportsman_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='c', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='slug',
            field=models.SlugField(default='s', max_length=255, verbose_name=True),
        ),
    ]
