# Generated by Django 4.2.5 on 2023-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0004_category_slug_sportsman_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name=True),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name=True),
        ),
    ]
